name: self-driving-module
channels:
  - defaults
dependencies:
  - pip=21.2.2
  - python=3.8.12
  - pip:
    - torch==1.9.0
    - seaborn==0.11.0
    - pandas==1.3.5
    - pyyaml==5.3.1
    - tqdm==4.50.2
    - flask==1.1.2
    - opencv-python==4.5.4.58
    - matplotlib==3.3.0
    - gunicorn==20.1.0
    - requests==2.24.0
    - numpy==1.19.4